name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Import GPG key
        if: ${{ secrets.GPG_KEY }} != ''
        run: |
          echo "${{ secrets.GPG_KEY }}" | gpg --batch --import

      - name: Release Maven package
        run: mvn -B deploy
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}