name: Tests

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.4.1'
    - name: Setup simulator
      uses: futureware-tech/simulator-action@v2
      with:
        model: 'iPhone 13'
      id: simulator
    - name: Install idb
      run: |
        brew update
        brew tap facebook/fb
        brew install idb-companion
    - name: Run idb companion
      run: |
        idb_companion --udid ${{steps.simulator.outputs.udid}} --grpc-port 10882 >idbLog.txt 2>&1 &
    - name: Build with Maven
      run: mvn clean -B package --file pom.xml -DskipTests
    - name: Echo idb_companion' processes
      run: |
        ps aux | grep idb
        lsof -i -P | grep idb
    - name: Test with Maven
      run: mvn test --file pom.xml
    - name: Print idb_companion' log
      if: always()
      run: |
        cat idbLog.txt
    - name: Stop idb
      if: always()
      run: |
        pkill idb_companion
